export const MODULES_LOCAL = [
    {
        title: "User",
        icon: "FiInbox",
        path: "user",
        parent: "app",
        route: "/app/user",
    },
    {
        title: "Log",
        icon: "PiDevToLogo",
        path: "logger",
        parent: "app",
        route: "/app/logger",
    },
    {
        title: "Suporte",
        icon: "MdOutlineSupportAgent",
        path: "suport",
        parent: "app",
        route: "/app/suport",
    },
    {
        title: "Ajuda",
        icon: "FiHelpCircle",
        path: "help",
        parent: "app",
        route: "/app/help",
    },
    {
        title: "Politica de privacidade",
        icon: "MdOutlinePrivacyTip",
        path: "privacypolicy",
        parent: "app",
        route: "/app/privacypolicy",
    },
    {
        title: "Termos de uso",
        icon: "AiOutlineAudit",
        path: "termsofuse",
        parent: "app",
        route: "/app/termsofuse",
    },
];

export const FAKER_MODULES = [
    {
        title: "Recepção",
        icon: "FiInbox",
        path: "recepcao",
        parent: "",
        route: "/recepcao",
    },
    {
        title: "Analítico",
        icon: "ImLab",
        path: "analitico",
        parent: "",
        route: "/analitico",
    },
    {
        title: "Almoxarifado",
        icon: "FiArchive",
        path: "almoxarifado",
        parent: "",
        route: "/almoxarifado",
    },
    {
        title: "LabOnline",
        icon: "FiGlobe",
        path: "labOnline",
        parent: "",
        route: "/labOnline",
    },
    {
        title: "Gerenciamento de Amostras",
        icon: "FiMonitor",
        path: "gerenciamentoDeAmostras",
        parent: "analitico",
        route: "/analitico/gerenciamentoDeAmostras",
    },
    {
        title: "Corrida Analítica",
        icon: "FiActivity",
        path: "corridaAnalitica",
        parent: "analitico",
        route: "/analitico/corridaAnalitica",
    },
    {
        title: "Rodada Analítica",
        icon: "AiOutlineDotChart",
        path: "rodadaAnalitica",
        parent: "analitico",
        route: "/analitico/rodadaAnalitica",
    },
    {
        title: "Entrada de Dados",
        icon: "FiBookOpen",
        path: "entradaDeDados",
        parent: "analitico",
        route: "/analitico/entradaDeDados",
    },
    {
        title: "Conferência de Resultados",
        icon: "BsClipboardCheck",
        path: "conferenciaDeResultados",
        parent: "analitico",
        route: "/analitico/conferenciaDeResultados",
    },
    {
        title: "Filtros",
        icon: "FiFilter",
        path: "filtros",
        parent: "gerenciamentoDeAmostras",
        route: "/analitico/gerenciamentoDeAmostras/filtros",
    },
    {
        title: "Detalhes",
        path: "detalhes",
        icon: "FiList",
        parent: "gerenciamentoDeAmostras",
        route: "/analitico/gerenciamentoDeAmostras/detalhes",
    },
    {
        title: "Filtros",
        icon: "FiFilter",
        path: "filtros",
        parent: "entradaDeDados",
        route: "/analitico/entradaDeDados/filtros",
    },
    {
        title: "Resultados",
        icon: "AiOutlineCalculator",
        path: "resultados",
        parent: "entradaDeDados",
        route: "/analitico/entradaDeDados/resultados",
    },
    {
        title: "Determinações",
        icon: "FiPackage",
        path: "determinacoes",
        parent: "resultados",
        route: "/analitico/entradaDeDados/resultados/determinacoes",
    },
    {
        title: "Determinações 2",
        icon: "FiPackage",
        path: "determinacoes2",
        parent: "resultados",
        route: "/analitico/entradaDeDados/resultados/determinacoes2",
    },
    {
        title: "Outros",
        icon: "FiPackage",
        path: "outros",
        parent: "determinacoes",
        route: "/analitico/entradaDeDados/resultados/determinacoes/outros",
    },
    {
        title: "Outros 2",
        icon: "FiPackage",
        path: "outros2",
        parent: "determinacoes",
        route: "/analitico/entradaDeDados/resultados/determinacoes/outros2",
    },
];
